spring:
  application.name: htmx-demo
  config.import: optional:file:.env[.properties] # enable scanning of .env file
  web.resources.cache.period: 365d

server:
  port: ${PORT:8087}
  forward-headers-strategy: framework # honor the original external request context (host, scheme, prefix)

management:
  endpoints:
    web.exposure.include: health,info,prometheus
  endpoint:
    health.probes.enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
